package com.cardconnect.langchain4j_spring.observability;

import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Timer;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.util.concurrent.TimeUnit;

/**
 * Custom metrics service for tracking AI agent performance.
 * Provides methods to record metrics for agent interactions.
 */
@Component
@Slf4j
public class AgentMetricsService {

    private final MeterRegistry meterRegistry;
    private final Counter totalRequestsCounter;
    private final Counter successfulRequestsCounter;
    private final Counter failedRequestsCounter;
    private final Timer agentResponseTimer;

    public AgentMetricsService(MeterRegistry meterRegistry) {
        this.meterRegistry = meterRegistry;

        // Initialize counters
        this.totalRequestsCounter = Counter.builder("agent.requests.total")
                .description("Total number of agent requests")
                .register(meterRegistry);

        this.successfulRequestsCounter = Counter.builder("agent.requests.success")
                .description("Number of successful agent requests")
                .register(meterRegistry);

        this.failedRequestsCounter = Counter.builder("agent.requests.failed")
                .description("Number of failed agent requests")
                .register(meterRegistry);

        this.agentResponseTimer = Timer.builder("agent.response.time")
                .description("Agent response time")
                .register(meterRegistry);
    }

    /**
     * Record a successful agent request
     */
    public void recordSuccess(String agentType, long durationMs) {
        totalRequestsCounter.increment();
        successfulRequestsCounter.increment();

        Counter.builder("agent.requests.by.type")
                .tag("agent", agentType)
                .tag("status", "success")
                .description("Agent requests by type")
                .register(meterRegistry)
                .increment();

        Timer.builder("agent.response.time.by.type")
                .tag("agent", agentType)
                .description("Response time by agent type")
                .register(meterRegistry)
                .record(durationMs, TimeUnit.MILLISECONDS);

        log.debug("Recorded successful {} agent request: {}ms", agentType, durationMs);
    }

    /**
     * Record a failed agent request
     */
    public void recordFailure(String agentType, String errorType) {
        totalRequestsCounter.increment();
        failedRequestsCounter.increment();

        Counter.builder("agent.requests.by.type")
                .tag("agent", agentType)
                .tag("status", "failed")
                .tag("error", errorType)
                .description("Agent requests by type")
                .register(meterRegistry)
                .increment();

        log.warn("Recorded failed {} agent request: {}", agentType, errorType);
    }

    /**
     * Record token usage for LLM calls
     */
    public void recordTokenUsage(String agentType, int inputTokens, int outputTokens) {
        Counter.builder("agent.tokens.input")
                .tag("agent", agentType)
                .description("Input tokens used by agent")
                .register(meterRegistry)
                .increment(inputTokens);

        Counter.builder("agent.tokens.output")
                .tag("agent", agentType)
                .description("Output tokens generated by agent")
                .register(meterRegistry)
                .increment(outputTokens);

        log.debug("Recorded token usage for {}: input={}, output={}", agentType, inputTokens, outputTokens);
    }

    /**
     * Record tool invocation
     */
    public void recordToolInvocation(String toolName, boolean success) {
        Counter.builder("agent.tool.invocations")
                .tag("tool", toolName)
                .tag("status", success ? "success" : "failed")
                .description("Tool invocation count")
                .register(meterRegistry)
                .increment();

        log.debug("Recorded tool invocation: {} - {}", toolName, success ? "success" : "failed");
    }

    /**
     * Record RAG retrieval metrics
     */
    public void recordRagRetrieval(int documentsRetrieved, double averageScore) {
        Counter.builder("rag.documents.retrieved")
                .description("Number of documents retrieved")
                .register(meterRegistry)
                .increment(documentsRetrieved);

        meterRegistry.gauge("rag.average.score", averageScore);

        log.debug("Recorded RAG retrieval: documents={}, avgScore={}", documentsRetrieved, averageScore);
    }
}

